In [1]:
import numpy as np

In [ ]:
#Q1

In [21]:
a=np.array([0,1,2,3,4,5,6,7,8])

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
b=a.reshape(3,3)

In [24]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
#Q2

In [26]:
c=np.array([0,1,2,3,4,5,6,7,8,9])

In [28]:
for i in range(len(c)):
    if(i%2==1):
        c[i]=-1
print(c)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [29]:
#Q3

In [44]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

In [47]:
h=np.where(x>y)
i=np.where(y==x)

In [49]:
print(h)
print("and")
print(i)

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
and
(array([0]),)


In [ ]:
#Q4

In [31]:
sri=np.arange(100).reshape(5,-1)

In [46]:
print(sri[:,:4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [50]:
#additional Q1

In [58]:
k=np.random.randint(30,40,10)
k

array([34, 31, 32, 31, 32, 34, 33, 36, 36, 30])

In [51]:
#additional Q2


In [71]:
A=np.array([[1,2,3],[4,5,6],[7,8,10]])
B=np.array([[7,8,10],[4,5,6],[1,2,3]])

In [72]:
C=A-B
print(C)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]


In [73]:
E=A-B
print(E)

[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


In [75]:
print(A.sum())
print(B.sum(axis=0))
print(C.sum(axis=1))


46
[12 15 19]
[31 30 31]


In [76]:
D=A*B
print(D)

[[ 7 16 30]
 [16 25 36]
 [ 7 16 30]]


In [77]:
C.sort(axis=0)
print(C)
print(E)

[[ 8 10 12]
 [ 8 10 13]
 [ 8 10 13]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


In [79]:
transposeE=E.transpose()
print(transposeE)

[[-6  0  6]
 [-6  0  6]
 [-7  0  7]]
